# Generated by Django 4.0.6 on 2022-10-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.RemoveField(
            model_name='user',
            name='test2',
        ),
    ]
