# Generated by Django 4.0.6 on 2022-10-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('Normaluser', 'Normal users of Shutter.'), ('StudioUser', 'Studio users of Shutter'))},
        ),
    ]
