# Generated by Django 4.0.6 on 2022-12-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtime',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
