# Generated by Django 4.0.6 on 2022-11-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='address',
            field=models.CharField(blank=True, default='address', max_length=50),
        ),
        migrations.AlterField(
            model_name='studio',
            name='close_time',
            field=models.CharField(blank=True, default='closeTime', max_length=50),
        ),
        migrations.AlterField(
            model_name='studio',
            name='instagram_link',
            field=models.CharField(blank=True, default='instagram_link', max_length=200),
        ),
        migrations.AlterField(
            model_name='studio',
            name='naver_link',
            field=models.CharField(blank=True, default='naver_link', max_length=200),
        ),
        migrations.AlterField(
            model_name='studio',
            name='open_time',
            field=models.CharField(blank=True, default='openTime', max_length=50),
        ),
        migrations.AlterField(
            model_name='studio',
            name='phone',
            field=models.CharField(blank=True, default='010-0000-0000', max_length=50),
        ),
        migrations.AlterField(
            model_name='studio',
            name='thumbnail',
            field=models.CharField(blank=True, default='url', max_length=500),
        ),
        migrations.AlterField(
            model_name='studio',
            name='town',
            field=models.CharField(blank=True, default='town', max_length=50),
        ),
    ]
