# Generated by Django 4.0.6 on 2022-10-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedtime',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='openedtime',
            name='minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
