# Generated by Django 4.0.6 on 2022-10-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_openedtime_hour_alter_openedtime_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=10000),
        ),
    ]
