# Generated by Django 4.0.6 on 2022-11-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_studio_address_alter_studio_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
