# Generated by Django 4.0.6 on 2022-11-08 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0002_alter_studio_address_alter_studio_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='close_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='follow_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='studio_follows', through='studio.Follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studio',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='naver_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='open_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
