# Generated by Django 4.0.6 on 2022-10-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='address',
            field=models.CharField(default='address', max_length=50),
        ),
        migrations.AddField(
            model_name='studio',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='studio',
            name='phone',
            field=models.CharField(default='010-0000-0000', max_length=50),
        ),
    ]
