# Generated by Django 4.0.6 on 2022-12-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_studio_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='product_description', max_length=500),
        ),
    ]
