# Generated by Django 4.0.6 on 2022-10-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_state'),
        ('studio', '0004_studio_address_studio_description_studio_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssginedTime',
            new_name='AssignedTime',
        ),
    ]
