# Generated by Django 4.0.6 on 2022-10-22 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_rename_assginedtime_assignedtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='address',
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='place_name', max_length=100)),
                ('description', models.CharField(default='place_description', max_length=500)),
                ('address', models.CharField(default='address', max_length=50)),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.studio')),
            ],
        ),
    ]
