# Generated by Django 4.0.6 on 2022-10-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_rename_assginedtime_assignedtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedtime',
            old_name='is_absence',
            new_name='is_available',
        ),
    ]
