# Generated by Django 4.0.6 on 2022-10-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_remove_studio_address_place'),
        ('studio', '0006_rename_is_absence_assignedtime_is_available'),
    ]

    operations = [
    ]
