# Generated by Django 4.0.6 on 2022-10-24 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_alter_user_options'),
        ('studio', '0007_merge_20221024_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'follow',
            },
        ),
        migrations.AddField(
            model_name='studio',
            name='address',
            field=models.CharField(default='address', max_length=50),
        ),
        migrations.AddField(
            model_name='studio',
            name='closeTime',
            field=models.CharField(default='closeTime', max_length=50),
        ),
        migrations.AddField(
            model_name='studio',
            name='follow_users',
            field=models.ManyToManyField(blank=True, related_name='studio_follows', through='studio.Follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studio',
            name='openTime',
            field=models.CharField(default='openTime', max_length=50),
        ),
        migrations.AddField(
            model_name='studio',
            name='photoshop',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=0),
        ),
        migrations.AddField(
            model_name='studio',
            name='thumbnail',
            field=models.CharField(default='url', max_length=500),
        ),
        migrations.AddField(
            model_name='studio',
            name='town',
            field=models.CharField(default='town', max_length=50),
        ),
        migrations.CreateModel(
            name='StudioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='url', max_length=500)),
                ('studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='review', max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.studio')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddField(
            model_name='follow',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.studio'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
