# Generated by Django 4.0.6 on 2022-10-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_merge_20221023_1642'),
        ('studio', '0007_merge_20221024_1207'),
    ]

    operations = [
    ]
