# Generated by Django 4.0.6 on 2022-10-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_merge_20221023_1642'),
        ('studio', '0008_follow_studio_address_studio_closetime_and_more'),
    ]

    operations = [
    ]
