# Generated by Django 4.0.6 on 2022-10-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_merge_20221024_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='closeTime',
            new_name='close_time',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='openTime',
            new_name='open_time',
        ),
    ]
