# Generated by Django 4.0.6 on 2022-10-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_alter_studioimage_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='instagram_link',
            field=models.CharField(default='instagram_link', max_length=200),
        ),
        migrations.AddField(
            model_name='studio',
            name='naver_link',
            field=models.CharField(default='naver_link', max_length=200),
        ),
    ]
