# Generated by Django 4.0.6 on 2022-11-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_price'),
        ('tags', '0002_phototag_remove_tag_photo_tag_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', through='tags.PhotoTag', to='photo.photo'),
        ),
    ]
