# Generated by Django 4.0.6 on 2022-11-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_created_at_photo_index'),
        ('tags', '0003_alter_tag_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='tags', through='tags.PhotoTag', to='photo.photo'),
        ),
    ]
