# Generated by Django 4.0.6 on 2022-10-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='reservation',
            name='state',
            field=models.IntegerField(choices=[(1, 'not_confirmed'), (2, 'confirmed'), (3, 'canceled')], default=1),
        ),
    ]
