# Generated by Django 4.0.6 on 2022-11-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='reservation',
        ),
    ]
