# Generated by Django 4.0.6 on 2022-12-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
