# Generated by Django 4.0.6 on 2022-10-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_is_confirmed_reservation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.IntegerField(choices=[(1, 'not_confirmed'), (2, 'confirmed'), (3, 'canceled'), (4, 'done')], default=1),
        ),
    ]
