# Generated by Django 4.0.6 on 2022-12-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.IntegerField(choices=[(1, '예약전'), (2, '예약완료'), (3, 'canceled'), (4, '입금완료'), (5, '예약반려')], default=1),
        ),
    ]
