# Generated by Django 4.0.6 on 2022-10-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_remove_studio_address_place'),
        ('reservation', '0003_alter_reservation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.place'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.studio'),
        ),
    ]
