# Generated by Django 4.0.6 on 2022-10-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_rename_assginedtime_assignedtime'),
        ('reservation', '0004_reservation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.studio'),
        ),
    ]
