# Generated by Django 4.0.6 on 2022-10-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_product_reservation_studio'),
        ('reservation', '0005_reservation_studio'),
    ]

    operations = [
    ]
