# Generated by Django 4.0.6 on 2022-11-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='color',
            field=models.IntegerField(blank=True, choices=[(1, '봄 웜톤'), (2, '여름 쿨톤'), (3, '가을 웜톤'), (4, '겨울 쿨톤'), (5, '흑백')], null=True),
        ),
    ]
