# Generated by Django 4.0.6 on 2022-10-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_rename_photourl_photo_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20),
        ),
    ]
