# Generated by Django 4.0.6 on 2022-11-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_color'),
        ('photo', '0003_photo_created_at_photo_index'),
    ]

    operations = [
    ]
